module.exports = {
  STATUS_CODE: {
    OK: 200,
    ACCEPTED: 202,
    NO_CONTENT: 204,
    INFO: 250,
    BAD_REQUEST: 400,
    UN_AUTHORIZED: 401,
    FORBIDDEN: 403,
    RESOURCE_NOT_FOUND: 404,
    TOO_MANY_REQUESTS: 429,
    VALIDATION_FAILURE: 450,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
    SERVER_TIMEOUT: 504,
  },
  ERROR_MSGS: {
    AUTH_FAIL: 'Authentication failed.',
    AUTH_HEADER_MISSING: 'AccessKey and SecretKey is required',
    INVALID_AUTH_HEADER: 'AccessKey and SecretKey is not valid',
    INACTIVE_STATE: 'Subscription is not in active state',
    INVALID_SUBSCRIPTION: 'Subscription is not valid',
    TOKEN_MISSING: 'No token provided',
    TOKEN_SESSION_EXPIRED: 'Token session expired',
    INVALID_TOKEN_FORMAT: 'Token invalid format',
  },
  INFO_MSGS: {
    NO_DATA: 'No data found',
    SUCCESS: 'Request success',
    PROCESSING: 'Request is currently in progress',
    YET_TO_PROCESS: 'Request is yet to process',
    UPDATED: 'Updated successfully',
  },
};
